name = input("What's your name? ")
print("Hi, " + name + "! It's nice to meet you.")
age = input("How old are you? ")
print("What a coincidence! I'm " + age + " too.")
print("I think I saw your girlfriend recently.")
gf_name = input("What's her name again? ")
print("Yea " + gf_name + "!")
print("That silly little kid!")
print("Forget about her and let's play a game.")
item_name = input("Give me anything and I can make it valuable. ")
print("Jiu's " + item_name)
print("Well, it definitely worth a lot.")
price = input("How much will you pay for it? $")
print("Don't be kidding. I think $" + price + "00000 makes more sense.")

