print("Hi, I'm a super calculator.")
print("Give me 2 numbers, however big they are, I can add them up in seconds.")
num1 = input("First number: ")
num2 = input("Second number: ")
print(num1)
print(num2)
result = float(num1) + float(num2)
print(float(num1) + float(num2))
print(result)