two_q = ["ckh", "swd", "dbk", 30000, "chi"]
three_q = ["lkc", "moth", "yyh"]
two_q.extend(three_q)
print(two_q)
three_q.append("wwy")
two_q.insert(-2, "pig")
three_q.remove("moth")
two_q.remove("ckh")
print(two_q + three_q)
three_q.pop()
print(three_q)
print(three_q.pop())
print(three_q)
print(len(two_q))
print(two_q[1])
print(two_q.index(30000))
print(two_q)
two_q.reverse()
print(two_q)
twoq = two_q.copy()
twoq.remove(30000)
twoq.sort()
twoq[1] = "lol"
print(twoq)
